### ISSUE TITLE
Настройка "ликвидировать позиции"

### ISSUE THREAD

**Issue by esemi** [esemi/backtester#221]
DOD
---
- у бота есть настройка "режим ликвидации" с активацией по тригеру текущей цены
- если режим включился - бот ничего не покупает и не продаёт обычными механизмами
- в этом режиме бот собирает все заявки с руки в одну и выставляет на продажу в режиме "продать по текущей цене, можно частично"
- бот ждёт 5 минут, пока заявка заполинтся
- если заявка заполнена полностью - бот удаляет стейт и заканчивает работу
- если заявка исполнена частично - бот отменяет заявку и ставит новую, с ценой на 5% ниже
- перевыставление заявок происходит не более 5 раз
- если заявка так и не продана - бот пишет об этом в логи, удаляет стейт и завершает работу
- после ликвидации бот пишет в статсу остаток непроданных монет (если остался) (result.json + mysql table)

**Comment by Sergey16021984** [comment]
а есть возможность не писать в логи а писать в файл json чтоб я мог на морде это видеть что с ним происходит

**Comment by esemi** [comment]
ну и сразу подсвечу, что ликвидация судя по всему может занять 25 минут времени работы бота
если вы этот промежуток бота перезапустить - то стейт ликвидации будет потерян и может поехать чтото
это можно обмазать тоже, но чёт займёт столько времени, что кмк пока оно того не стоит
но держать в уме стоит, что ликвидация не стейтобезопасная сейчас будет
